# https://packaging.python.org/en/latest/appveyor/

environment:
  global:
    REPO_DIR: orange3
    STAGING_INDEX: https://pypi.anaconda.org/ales-erjavec/simple
    GIT_COMMIT: 3.3.3
    # ANACONDA_USERNAME: ales-erjavec
    # ANACONDA_PASSWORD:
    #     secure: ...

  matrix:
    - PYTHON: "C:\\Python34"

    - PYTHON: "C:\\Python34-x64"

    - PYTHON: "C:\\Python35"

    - PYTHON: "C:\\Python35-x64"

cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  - "%PYTHON%\\python -m pip install wheel==0.26.* pip==8.1.*"
  - "%PYTHON%\\python -m pip install --extra-index-url %STAGING_INDEX% --only-binary numpy numpy==1.9.3"

build_script:
  - git submodule update --init
  - cd %REPO_DIR%
  - git checkout %GIT_COMMIT%
  - cd ..
  - "%PYTHON%\\python -m pip wheel --no-deps -w dist ./%REPO_DIR%"

test_script:
  - "%PYTHON%\\python -m venv --clear %USERPROFILE%\\testenv"
  - "%USERPROFILE%\\testenv\\Scripts\\activate"
#  - python -c "import sys; print(sys.prefix)"
#  - python -c "import sys; print(sys.version)"
#  - python -m pip install pip==8.1.*
#  - python -m pip install --no-deps --no-index --find-links dist Orange
#  - python -m pip install --extra-index-url %STAGING_INDEX%  --only-binary numpy,scipy,bottlechest,scikit-learn Orange
#  - python -m unittest -v Orange.tests

artifacts:
  - path: dist\*
